### ISSUE TITLE
Error: Unknown transformation name amd

### ISSUE THREAD

**Issue by roschaefer** [kinesisptyltd/ember-chroma-shim#39]
After updating to `ember-cli` version 2.16.0 I encounter this error when I do `ember serve`:
```
$ ember serve
while import vendor/chromajs/chroma.js: found an unknown transformation name amd. Available transformNames are:
Error: while import vendor/chromajs/chroma.js: found an unknown transformation name amd. Available transformNames are:
    at options.using.forEach.entry (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1688:19)
    at Array.forEach (<anonymous>:null:null)
    at EmberApp._import (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1679:23)
    at EmberApp.import (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1652:10)
    at Class.included (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-chroma-shim/index.js:13:15)
    at project.addons.project.addons.filter.addon (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:545:17)
    at Array.filter (<anonymous>:null:null)
    at EmberApp._notifyAddonIncluded (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:542:47)
    at new EmberApp (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:147:10)
    at module.exports (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/ember-cli-build.js:5:13)
    at Builder.setupBroccoliBuilder (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at Promise.resolve.then (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatch (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/robert/Development/Rails/rundfunk-mitbestimmen/frontend/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
https://travis-ci.org/roschaefer/rundfunk-mitbestimmen/builds/285948319#L1397

Even if this repository might not be maintained, maybe it's worth to report it anyways.

**Comment by roschaefer** [comment]
OK, this is a bug in `ember-cli`: https://github.com/ember-cli/ember-cli/issues/7370
